### ISSUE TITLE
Data from feedback form not stored

### ISSUE THREAD

**Issue by nehalchakravarthy** [nehalchakravarthy/web-dev#2]
The data entered in feedback form in contact page is not stored anyway. Rather it's simply discarded and redirected to the feedback submitted page.

**Comment by Gr8ayu** [comment]
This can be implemented to store data in google sheet https://blog.webjeda.com/google-form-customize/

**Comment by nehalchakravarthy** [comment]
Thanks @Gr8ayu , I implemented it.
